services:
  taccso-api:
    image: ghcr.io/ayushkmr/taccso/taccso:1.1.7  # Your custom TAccSo API image
    container_name: TAccSo-API  # Renamed container
    ports:
      - "3080:3080"
    depends_on:
      - taccso-mongodb
      - taccso-rag-api
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://taccso-mongodb:27017/TAccSo  # Updated database name and host
      - MEILI_HOST=http://taccso-meilisearch:7700  # Updated host
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://taccso-rag-api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: ./taccso.yaml  # Renamed configuration file
        target: /app/librechat.yaml  # Application expects this path
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs

  taccso-mongodb:
    image: mongo
    container_name: taccso-mongodb  # Renamed container
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

  taccso-meilisearch:
    image: getmeili/meilisearch:v1.7.3
    container_name: taccso-meilisearch  # Renamed container
    restart: always
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://taccso-meilisearch:7700  # Updated host
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.7:/meili_data

  taccso-vectordb:
    image: ankane/pgvector:latest
    container_name: taccso-vectordb  # Renamed container
    environment:
      - POSTGRES_DB=taccsodb  # Updated database name
      - POSTGRES_USER=taccsouser
      - POSTGRES_PASSWORD=your_secure_password  # Ensure this is secure
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data

  taccso-rag-api:
    image: ghcr.io/ayushkmr/taccso/taccso-rag-api:1.1.7  # Your custom RAG API image
    container_name: TAccSo-RAG-API  # Renamed container
    environment:
      - DB_HOST=taccso-vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - taccso-vectordb
    env_file:
      - .env

volumes:
  pgdata2:
