services:
  api:
    container_name: TAccSo
    image: ghcr.io/ayushkmr/taccso/taccso:latest
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "${PORT:-3080}:${PORT:-3080}"
    depends_on:
      - mongodb
      - rag_api
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=${PORT:-3080}
      - MONGO_URI=mongodb://mongodb:27017/TAccSo
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - type: bind
        source: ./taccso.yaml
        target: /app/taccso.yaml
      - ./images:/app/client/public/images
      - ./logs:/app/api/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    container_name: taccso-mongodb
    image: mongo
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

  meilisearch:
    container_name: taccso-meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: always
    user: "${UID}:${GID}"
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.7:/meili_data

  vectordb:
    container_name: vectordb
    image: ankane/pgvector:latest
    restart: always
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}

volumes:
  pgdata2: